# Generated by Django 5.2.3 on 2025-06-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_user_is_active_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
