# Generated by Django 5.2.6 on 2025-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_education_instructorprofile_teachingexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
