# Generated by Django 5.2.6 on 2025-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_importantdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantdocument',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
