# Generated by Django 5.2.6 on 2025-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_importantdocument_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='email_domain',
            field=models.CharField(max_length=255),
        ),
    ]
