# Generated by Django 5.2.6 on 2025-10-10 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='lms_app.university'),
        ),
    ]
