# Generated by Django 5.2.6 on 2025-10-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0018_alter_course_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
