# Generated by Django 5.2.6 on 2025-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0019_alter_course_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='courses/banners/'),
        ),
    ]
