# Generated by Django 5.2.6 on 2025-10-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0022_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms_app.curriculum'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enroll_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6),
        ),
    ]
