# Generated by Django 5.2.6 on 2025-10-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0023_alter_course_curriculum_alter_course_enroll_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='chapters/covers/'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chapters/materials/'),
        ),
    ]
