# Generated by Django 5.2.6 on 2025-10-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0024_coursechapter_cover_image_coursematerial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_covers/'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
