# Generated by Django 5.2.6 on 2025-10-27 04:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0025_alter_coursechapter_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring', to='lms_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('incorrect', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms_app.scoring')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
