# Generated by Django 5.2.6 on 2025-10-28 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0026_scoring_scoringitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Document'), ('pdf', 'Pdf'), ('doc', 'Doc'), ('url', 'Url'), ('image', 'Image'), ('notebook', 'Notebook'), ('interactive', 'Interactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ผู้ดูแล'), ('INSTRUCTOR', 'ผู้สอน'), ('STUDENT', 'นักเรียน')], db_index=True, default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lms_app.course')),
            ],
            options={
                'ordering': ['course_id'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=32)),
                ('title', models.TextField(blank=True, null=True)),
                ('text_parts', models.JSONField(blank=True, default=list)),
                ('correct_answers', models.JSONField(blank=True, default=list)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms_app.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lms_app.quizquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uq_quiz_order'),
        ),
    ]
