# Generated by Django 5.2.6 on 2025-10-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0027_alter_coursematerial_path_alter_coursematerial_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='serial_no',
            field=models.CharField(db_index=True, default='TEMP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(default='INIT', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_url',
        ),
    ]
