# Generated by Django 5.2.6 on 2025-11-03 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0029_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='serial_no',
            field=models.CharField(db_index=True, default='TEMP', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(db_index=True, default='TEMP', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
