# Generated by Django 5.2.6 on 2025-11-06 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0030_certificate_issued_at_certificate_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={},
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='instructor_display',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='course_title_override',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='issuer_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='locale',
            field=models.CharField(default='th', max_length=8),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='style',
            field=models.CharField(default='classic', max_length=32),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_template', to='lms_app.course'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='primary_color',
            field=models.CharField(default='#881337', max_length=7),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='secondary_color',
            field=models.CharField(default='#1f2937', max_length=7),
        ),
        migrations.AlterField(
            model_name='coursepricing',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='lms_app.course'),
        ),
    ]
