# Generated by Django 5.2.6 on 2025-11-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0031_alter_certificatetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assign_to_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms_app.coursechapter'),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
