# Generated by Django 5.2.6 on 2025-11-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0032_assignment_assign_to_code_assignment_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.FloatField(default=100.0),
        ),
    ]
