# Generated by Django 5.2.6 on 2025-11-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0033_alter_assignment_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachment',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
