# Generated by Django 5.2.6 on 2025-11-14 04:49

import lms_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0034_alter_assignmentattachment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=lms_app.storage.NormalizedStorage(), upload_to='assignments/%Y/%m/'),
        ),
    ]
