# Generated by Django 5.2.6 on 2025-11-14 04:55

import lms_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0035_alter_assignmentattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, storage=lms_app.storage.NormalizedStorage(), upload_to='chapters/materials/'),
        ),
        migrations.AlterField(
            model_name='importantdocument',
            name='file',
            field=models.FileField(storage=lms_app.storage.NormalizedStorage(), upload_to='important_docs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=lms_app.storage.NormalizedStorage(), upload_to='profiles/'),
        ),
    ]
