# Generated by Django 5.2.6 on 2025-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0036_alter_coursematerial_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, help_text='จำนวนชั่วโมงของคอร์ส', null=True),
        ),
    ]
