# Generated by Django 5.2.6 on 2025-11-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0037_course_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitymember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ผู้ดูแล'), ('INSTRUCTOR', 'ผู้สอน'), ('STUDENT', 'นักเรียน'), ('UNIVERSITY', 'มหาวิทยาลัย')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ผู้ดูแล'), ('INSTRUCTOR', 'ผู้สอน'), ('STUDENT', 'นักเรียน'), ('UNIVERSITY', 'มหาวิทยาลัย')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
