"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os, sys
if sys.platform.startswith("win"):
    # โฟลเดอร์ DLL ของ MSYS2 UCRT64 ที่เราติดตั้ง pango/cairo/glib ไว้
    dll_dir = r"C:\msys64\ucrt64\bin"
    if os.path.isdir(dll_dir):
        try:
            os.add_dll_directory(dll_dir)
        except Exception:
            # บางเวอร์ชันของ Python เก่าอาจไม่มี os.add_dll_directory (แต่ 3.13 มี)
            os.environ["PATH"] = dll_dir + os.pathsep + os.environ.get("PATH", "")
            
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / "env")   # ✅ โหลดไฟล์ .env ที่อยู่ข้างๆ manage.py

# Build paths inside the project like this: BASE_DIR / 'subdir'.
 

AUTH_USER_MODEL = 'lms_app.User'  # Custom user model


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/f

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0p0=)9lsf7t48_jj+hvfj2d$dg&x8j3l($b(5t()c_5*(pe&r-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]  # ✅ ใช้ให้คงที่กับฝั่ง Front

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'allauth',             
    'allauth.account',   
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'lms_app',

    'dj_rest_auth',
    
]

PASSWORD_RESET_CONFIRM_URL = "reset-password?uid={uid}&token={token}"

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'allauth.account.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'lms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'lms_db'),
        'USER': os.environ.get('POSTGRES_USER', 'lms_admin'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'lms_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"        # ใน dev ส่วนมากเป็น http# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # เพิ่มบรรทัดนี้ (สำคัญสำหรับอัปโหลดไฟล์)
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "20/hour",  # ตัวอย่าง: จำกัดรวมทั้งระบบ
    },
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = False  # for dev naja
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     # production domain
# ]

# Authentication backends
AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Allauth Settings
# ปิดการใช้ Username, บังคับใช้อีเมลเป็นหลัก
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'optional' # ตั้งเป็น none เพื่อความง่ายในช่วงพัฒนา

# Social Account settings
import os

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
            "key": ""
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}




REST_AUTH_TOKEN_MODEL = None
DJ_REST_AUTH = {
    "USE_JWT": True,
    "TOKEN_MODEL": None,
    "SESSION_LOGIN": False,
}
# Custom serializer for user registration
# This setting allows us to customize the registration process by specifying which serializer to use
# The default RegisterSerializer from dj-rest-auth is used here



SOCIALACCOUNT_ADAPTER = 'lms_app.adapter.MySocialAccountAdapter'





SPECTACULAR_SETTINGS = {
    'TITLE': 'LMS Project API',
    'DESCRIPTION': 'API documentation for the Learning Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

        # ถ้าเจอชน component name ระหว่าง dj_rest_auth กับ simplejwt
    "COMPONENT_NAME_OVERRIDES": {
        "TokenRefresh": "SimpleJWTTokenRefresh",   # เคสชนชื่อ TokenRefresh
        # "UserDetails": "AppUserDetails",  # เราแก้ใน serializer ด้วย ref_name แล้ว ไม่จำเป็นต้องใส่ซ้ำ
    },
}
# --- ค่า callback ใช้ร่วมกับ view GoogleLogin ---
GOOGLE_CALLBACK_URL = os.environ.get(
    "GOOGLE_CALLBACK_URL",
    "http://localhost:3000/auth/callback"  # ต้องตรงกับ Front + Google Cloud
)
DEFAULT_UNIVERSITY_ID = os.getenv("DEFAULT_UNIVERSITY_ID")

LOGGING = {
    "version": 1,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": "INFO"},
}

import os

# ใช้ SMTP ของ Gmail (หรือ SMTP อื่นตามที่คุณใช้จริง)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")   # ✅ ค่า default เป็น smtp.gmail.com
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))         # ✅ Gmail ใช้พอร์ต 587 (TLS)
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_USE_SSL = False                                    # ✅ Gmail ไม่ใช้ SSL (465)

# 👇 ต้องใส่ค่าใน .env ให้ครบ
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")           # ✅ อีเมลจริงของคุณ เช่น mymail@gmail.com
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")   # ✅ App Password ของ Gmail (ไม่ใช่รหัส Gmail ปกติ)

# ✅ ใส่ DEFAULT_FROM_EMAIL ให้ตรงกับอีเมลที่ใช้ส่ง (เพื่อไม่โดน block)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# ใช้สำหรับ render ข้อความในอีเมล (เช่น reset password link)
SITE_NAME = os.environ.get("SITE_NAME", "LMS")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")
CERT_RENDER_TOKEN = "your-long-random-token"

# ระยะเวลาที่ token reset password จะหมดอายุ (วินาที) → 1800s = 30 นาที
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", "1800"))

