# Generated by Django 5.2.3 on 2025-06-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_universitymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorinvitation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorinvitation',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_app.university'),
        ),
    ]
