# Generated by Django 5.2.3 on 2025-06-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_instructorinvitation_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enroll_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
