# Generated by Django 5.2.6 on 2025-09-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
